#!/bin/bash
# Script que detecta erros de estilo
# antes de serem submetidos em definitivo ao repositório.

dir=$(dirname $(readlink -f $0))

error=0
source "$dir/pre-commit.utilities.sh"
source "$dir/pre-commit.whitespace.sh"
source "$dir/pre-commit.aspell.sh"
source "$dir/pre-commit.forbidden.sh"
exit $error
